apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata: 
  labels: 
    name: nginx-rs 
  name: nginx-rs 
spec:  
  replicas: 3 
  selector:  
    matchLabels: 
      app: nginx-rs-pod 
  template:  
    metadata: 
      labels:  
        app: nginx-rs-pod 
    spec:  
      containers:  
      - image: nginx 
        name: nginx
         
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: k8-service
  name: k8-service
spec:
  selector:
    app: nginx-rs-pod
  ports:
  - name: service-port
    port: 81
    targetPort: 80
    protocol: TCP
  type: NodePort
