apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxtest
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-svc
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
